// src/components/Section.tsx
"use client";

import { motion } from "framer-motion";
import { ReactNode } from "react";
import { cn } from "@/lib/utils";

interface SectionProps {
    children: ReactNode;
    id?: string;
    className?: string;
    delay?: number;
}

export default function Section({
    children,
    id,
    className,
    delay = 0,
}: SectionProps) {
    return (
        <motion.section
            id={id}
            initial={{ opacity: 0, y: 50 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-100px" }}
            transition={{ duration: 0.8, delay }}
            className={cn("py-20 px-4 md:px-8 max-w-7xl mx-auto", className)}
        >
            {children}
        </motion.section>
    );
}

// src/lib/components/sections/Section.svelte
<script lang="ts">
	import { cn } from '$lib/utils';
	import { inview } from '$lib/actions/inview';
	import { fly } from 'svelte/transition';
	import type { HTMLAttributes } from 'svelte/elements';
	import type { Snippet } from 'svelte';

	interface Props extends HTMLAttributes<HTMLElement> {
		id?: string;
		class?: string;
		delay?: number;
		children?: Snippet;
	}

	let { id, class: className, delay = 0, children, ...rest }: Props = $props();

	let visible = $state(false);
</script>

<section
	{id}
	use:inview={{ threshold: 0.1, once: true, onEnter: () => (visible = true) }}
	class={cn('mx-auto max-w-7xl px-4 py-20 md:px-8', className)}
	{...rest}
>
	{#if visible}
		<div in:fly={{ y: 50, duration: 800, delay: delay * 1000 }}>
			{@render children?.()}
		</div>
	{/if}
</section>
