// src/lib/components/sections/Articles.svelte
<script lang="ts">
	import { ArrowUpRight, Heart } from 'lucide-svelte';
	import type { QiitaUser, QiitaArticle } from '$lib/qiita';

	interface Props {
		data: {
			qiita: {
				user: QiitaUser | null;
				topArticles: QiitaArticle[];
			};
		};
	}

	let { data }: Props = $props();

	let userData = $derived(data?.qiita?.user);
	let topArticles = $derived(data?.qiita?.topArticles);

	const QIITA_USER_ID = 'TaiyoYamada';
</script>

<section id="articles" class="bg-white py-20 md:py-28">
	<div class="mx-auto max-w-5xl px-5 md:px-8">
		<header class="mb-14 flex flex-col gap-6 md:mb-20 md:flex-row md:items-end md:justify-between">
			<div>
				<p class="mb-3 text-[11px] font-medium tracking-[0.2em] text-neutral-400 uppercase">
					Writing
				</p>
				<h1 class="text-5xl font-medium tracking-tight text-black md:text-7xl">Articles</h1>
			</div>
			{#if userData}
				<p class="text-sm text-neutral-500">
					{userData.items_count}
					<span class="text-neutral-400">posts on</span>
					Qiita
				</p>
			{/if}
		</header>

		{#if !topArticles || topArticles.length === 0}
			<div class="border-t border-black/10 py-16 text-center">
				<p class="text-sm text-neutral-500">記事を読み込めませんでした。</p>
				<a
					href={`https://qiita.com/${QIITA_USER_ID}`}
					target="_blank"
					rel="noopener noreferrer"
					class="mt-3 inline-flex items-center gap-1.5 text-sm font-medium text-black underline-offset-4 hover:underline"
				>
					Qiita で直接見る
					<ArrowUpRight size={14} />
				</a>
			</div>
		{:else}
			<ul class="divide-y divide-black/10 border-y border-black/10">
				{#each topArticles as article}
					<li>
						<a
							href={article.url}
							target="_blank"
							rel="noopener noreferrer"
							class="group -mx-4 grid grid-cols-[1fr_auto] gap-4 px-4 py-8 transition-colors hover:bg-black/[0.02] md:-mx-6 md:grid-cols-[1fr_auto_auto] md:gap-8 md:px-6 md:py-10"
						>
							<div class="min-w-0">
								<h2 class="text-lg leading-snug font-semibold tracking-tight text-black md:text-xl">
									{article.title}
								</h2>
								<div
									class="mt-3 flex flex-wrap gap-x-3 gap-y-1 text-xs text-neutral-500 md:text-sm"
								>
									{#each article.tags.slice(0, 4) as tag, i}
										<span>{tag.name}</span>
										{#if i < Math.min(article.tags.length, 4) - 1}
											<span class="text-neutral-300">·</span>
										{/if}
									{/each}
								</div>
							</div>

							<div
								class="flex items-center gap-1.5 self-start text-xs text-neutral-500 md:self-center"
							>
								<Heart size={12} strokeWidth={2} />
								<span class="font-mono">{article.likes_count}</span>
							</div>

							<div class="hidden self-center md:block">
								<ArrowUpRight
									size={16}
									class="text-neutral-300 transition-all group-hover:translate-x-0.5 group-hover:-translate-y-0.5 group-hover:text-black"
								/>
							</div>
						</a>
					</li>
				{/each}
			</ul>

			<div class="mt-10 flex justify-center">
				<a
					href={`https://qiita.com/${QIITA_USER_ID}`}
					target="_blank"
					rel="noopener noreferrer"
					class="group inline-flex items-center gap-2 text-sm font-medium text-neutral-500 transition-colors hover:text-black"
				>
					<span
						class="border-b border-neutral-300 pb-0.5 transition-colors group-hover:border-black"
						>View all on Qiita</span
					>
					<ArrowUpRight
						size={14}
						class="transition-transform group-hover:translate-x-0.5 group-hover:-translate-y-0.5"
					/>
				</a>
			</div>
		{/if}
	</div>
</section>

// src/components/Articles.tsx
import Section from "./Section";
import { Card } from "./ui/Card";
import { BookOpen, Heart } from "lucide-react";
import { getUser, getTopArticlesByLikes } from "@/lib/qiita";

const QIITA_USER_ID = "TaiyoYamada";

export default async function Articles() {
    try {
        // Fetch user data and top articles concurrently
        const [userData, topArticles] = await Promise.all([
            getUser(QIITA_USER_ID),
            getTopArticlesByLikes(QIITA_USER_ID, 3),
        ]);

        return (
            <Section id="articles" className="relative z-10">
                <h2 className="text-4xl md:text-5xl font-bold mb-8 text-center text-gradient">
                    Articles
                </h2>

                {/* Articles Count */}
                <div className="text-center mb-12">
                    <p className="text-gray-400 text-lg">
                        Qiita Articles：{" "}
                        <span className="text-primary font-bold text-2xl">
                            {userData.items_count}
                        </span>
                        {" "}articles
                    </p>
                </div>

                {/* Top 3 Articles by Likes */}
                <div className="space-y-4">
                    {topArticles.map((article, index) => (
                        <a
                            key={article.id}
                            href={article.url}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="block group"
                        >
                            <Card className="flex items-start gap-4 p-6 hover:bg-white/10 transition-colors">
                                <div className="mt-1 text-gray-500 group-hover:text-secondary transition-colors flex-shrink-0">
                                    <BookOpen size={20} />
                                </div>
                                <div className="flex-grow min-w-0">
                                    <div className="flex items-start justify-between gap-4 mb-2">
                                        <h3 className="text-lg font-bold text-white group-hover:text-primary transition-colors">
                                            {article.title}
                                        </h3>
                                        <div className="flex items-center gap-1 text-pink-400 flex-shrink-0">
                                            <Heart size={16} className="fill-current" />
                                            <span className="font-semibold">{article.likes_count}</span>
                                        </div>
                                    </div>
                                    {article.tags.length > 0 && (
                                        <div className="flex flex-wrap gap-2 mt-3">
                                            {article.tags.slice(0, 5).map((tag) => (
                                                <span
                                                    key={tag.name}
                                                    className="text-xs px-2 py-1 rounded-full bg-white/5 text-gray-400 border border-white/10"
                                                >
                                                    {tag.name}
                                                </span>
                                            ))}
                                        </div>
                                    )}
                                </div>
                            </Card>
                        </a>
                    ))}
                </div>

                {/* Link to Qiita Profile */}
                <div className="text-center mt-8">
                    <a
                        href={`https://qiita.com/${QIITA_USER_ID}`}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-gray-400 hover:text-primary transition-colors text-sm"
                    >
                        View all articles on Qiita →
                    </a>
                </div>
            </Section>
        );
    } catch (error) {
        console.error("Failed to fetch Qiita articles:", error);

        // Error fallback UI
        return (
            <Section id="articles" className="relative z-10">
                <h2 className="text-4xl md:text-5xl font-bold mb-16 text-center text-gradient">
                    Articles
                </h2>
                <div className="text-center text-gray-400">
                    <p>Unable to load articles at this time.</p>
                    <p className="text-sm mt-2">
                        Please visit{" "}
                        <a
                            href={`https://qiita.com/${QIITA_USER_ID}`}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="text-primary hover:underline"
                        >
                            my Qiita profile
                        </a>
                        {" "}directly.
                    </p>
                </div>
            </Section>
        );
    }
}
